Note port for rpm packages in post install section
artefactual/archivematica-docs pull request #103
Opened 2018-03-20 16:41 UTC by scollazo

Closes artefactual/archivematica-docs#92

2018-03-20 17:27 UTC, sevein requested changes
Nitpicks:
- Changes don't use 80cols.
- Things like 8001, 81, etc... could be inline literals for better readability.
- "RPM packages use port 8001" is a sentence, "(RPM packages use port 81)" however use parenthesis.

2018-03-20 19:04 UTC, scollazo commented
Changed to 80 columns, and added brackets  to both sentences.

Reading the section, I prefer to don't use inline, as there isn't any inline port in other paragraphs of the section.

2018-03-20 19:08 UTC, sevein requested changes

2018-03-20 19:08 UTC, sevein commented on admin-manual/installation/installation.rst
> +   of the machine you have been installing on ( RPM packages use port 8001 ).
Nitpick: typographical error, should read `(RPM packages use port 8001)` instead of `( RPM packages use port 8001 )`.

2018-03-20 19:08 UTC, sevein commented on admin-manual/installation/installation.rst
> +   web browser: http://localhost. Again, you can use the IP address of the machine you
^ this line has 86 cols

2018-03-21 16:19 UTC, sevein approved these changes
Thanks.

2018-03-21 16:48 UTC, merged