Add Postfix maintenance documentation
artefactual/archivematica-docs pull request #135
Opened 2018-04-23 21:31 UTC by mamedin

This fixes #130

2018-04-23 23:19 UTC, sevein requested changes

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +The standard mail server setup for Archivematica installs a postfix mail
s/postfix/Postfix

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +.. _centos:
It'd be best to choose a unique name like `_postfix-centos`.

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +.. _ubuntu:
It'd be best to choose a unique name like `_postfix-ubuntu`.

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +Other, more complex, postfix configurations are up to the sysadmins, as seen
Postfix instead of postfix (this happen a few times in your PR).

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +for Ubuntu.
You could use a link to point to the Ubuntu section.
Not tested:

```
in the :ref:`Ubuntu section above <postfix-ubuntu>`
```

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +When installing Postfix (which archivematica-mcp-client depends on), choose
You can use inline literals in cases like this one, it's visually nicer.

```
... (which ``archivematica-mcp-client`` depends on)...
```

2018-04-23 23:19 UTC, sevein commented on admin-manual/maintenance/maintenance.rst
> +configured as "Internet Site": A local mail server that sends emails directly
s/A local/a local

I don't think that you have to start the sentence after the colon with a capital letter.

2018-04-24 17:33 UTC, sallain reviewed
Looks good overall - I think sevein noted all the needed changes.

2018-04-24 18:20 UTC, mamedin commented
Thanks @sevein and @sallain , it is ready for CR again :)

2018-04-24 18:26 UTC, sevein approved these changes

2018-04-24 18:49 UTC, sallain approved these changes

2018-04-24 21:03 UTC, mamedin commented
Reopening and merging

2018-04-24 21:11 UTC, merged