Add ClamAV signatures check
artefactual/archivematica-docs pull request #145
Opened 2018-04-27 20:50 UTC by mamedin

Fixes #118

2018-04-27 21:08 UTC, sevein requested changes

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-centos.rst
> +        sudo chown clamupdate:clamupdate /var/lib/clamav/*cvd
sudo sudo? I guess we don't need that?

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-centos.rst
> +   * Enable and Start ClamAV daemon:
s/Start/start

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-centos.rst
> +        active
You could replace this with an inline literal.

> When the service is up, the output is: `active`.

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-ubuntu.rst
> +12. Check ClamAV signatures (optional). To run the clamav-daemon service, it
s/Check/Check out? Or maybe Download?

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-ubuntu.rst
> +    - main.cvd
^ they could be inline literals 

```
    - :file:`bytecode.cvd`
    - :file:`daily.cld` or :file:`daily.cvd`
    - :file:`main.cvd`
```

Even better using `:file:` (http://www.sphinx-doc.org/en/stable/markup/inline.html).

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-ubuntu.rst
> +    time clamav-freshclam is started it can sometimes take longer than 1
L161 and L162: inline literal for clamav-freshclam?

2018-04-27 21:08 UTC, sevein commented on admin-manual/installation-setup/installation/install-ubuntu.rst
> +    repository, running:
Another nitpick, `artefactual-labs/clamav-files` could be a hyperlink too.
See http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets.

2018-04-27 22:20 UTC, sallain requested changes

2018-04-27 22:20 UTC, sallain commented on admin-manual/installation-setup/installation/install-centos.rst
> +     If the deemon has not started, please check the above section.
Deemon should be daemon (though deemon sounds a lot more cute). It appears a few times below, as well.

2018-04-27 22:20 UTC, sallain commented on admin-manual/installation-setup/installation/install-ubuntu.rst
> +    If the deemon has not started, please check the above section.
Which above section? Hyperlinking to it by name would be great.

2018-04-28 17:02 UTC, sevein commented
@mamedin I think that your branch has been deleted because you pushed it to the public remote.

2018-04-28 20:30 UTC, sevein commented
I've just rescued it for you using the PR's remote that GH provides (if you're curious, you can do that following the instructions here: https://help.github.com/articles/checking-out-pull-requests-locally/).

2018-04-28 20:32 UTC, sevein commented
@mamedin I wanted to try to push most recent signature files to the clamav-files repo but I've learned that the files are already too big to be managed by GH repos without lfs.

What I've done instead is to create a new release that I've called `20180428` and uploaded the files to it from the command line interface.

I have new snippets that you may want to try:

For CentOS:

```
yum install -y wget
wget -nv -nc -P /var/lib/clamav \
    https://github.com/artefactual-labs/clamav-files/releases/download/20180428/main.cvd \
    https://github.com/artefactual-labs/clamav-files/releases/download/20180428/daily.cvd \
    https://github.com/artefactual-labs/clamav-files/releases/download/20180428/bytecode.cvd
chown clamupdate:clamupdate /var/lib/clamav/*cvd
```

For Ubuntu:

```
wget -nc -P /var/lib/clamav \
    https://github.com/artefactual-labs/clamav-files/releases/download/20180428/main.cvd \
    https://github.com/artefactual-labs/clamav-files/releases/download/20180428/daily.cvd \
    https://github.com/artefactual-labs/clamav-files/releases/download/20180428/bytecode.cvd
chown clamav:clamav /var/lib/clamav/*cvd
```

2018-04-30 19:26 UTC, mamedin commented
@sallain , @sevein thanks very much for your suggestions. I have changed all that you said in your comments. This PR is ready again for CR

2018-04-30 19:50 UTC, sevein approved these changes

2018-04-30 20:31 UTC, sallain approved these changes

2018-05-01 16:35 UTC, merged