Expands TRAC acronym and tidies up explanatory text
artefactual/archivematica-docs pull request #187
Opened 2018-07-15 12:31 UTC by sallain

Connected to archivematica/issues#12

2018-07-17 13:53 UTC, ross-spencer commented on getting-started/other-resources/trac.rst
> +The review tool was developed by MIT in a project led by Nancy McGovern, Head of
Hi @sallain there are two lines in this paragraph going over 80 characters. If we can correct those that will be good.

2018-07-17 13:57 UTC, ross-spencer requested changes
Hi @sallain. In the introduced changes lines 7, 14, and 15 extend over 80 characters. If these can be fixed that will be good. I notice also in the main body, a few lines with hyperlinks that extend over 80 characters too. I wonder if there is an opportunity, whether you can fix this to [reference style-links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) while you're in the doc to bring the whole page up to date with the style guide. No worries if not. The line changes in the newly introduced text are probably more important.The text itself looks great.

2018-07-17 14:02 UTC, sallain commented
@ross-spencer Working on adding reference-style links right now! You're a mind reader.

2018-07-17 14:25 UTC, sallain commented
@ross-spencer I've fixed those line lengths and redone all the links. Should be compliant with our style guide now.

2018-08-15 22:13 UTC, ross-spencer approved these changes

2018-08-15 22:20 UTC, merged