Update Administration Tab pages
artefactual/archivematica-docs pull request #198
Opened 2018-09-13 23:43 UTC by sallain

This change was a bit of a rabbit hole - I started out updating the config
information for ArchivesSpace DIP uploads and then realized that a good clean-
up was in order.

Note that there are two pages that contain the bulk of the changes:
* User Manual > Administer > Dashboard administration tab
* Admin Manual > Installation and setup > Customizations > Dashboard administration tab

The latter already existed, but was not linked from anywhere except the admin
manual index, which is not normally accessed by users unless they end up there
via the search. I've now linked this page from the Customizations page.

In terms of content, I've attempted to remove administrator-level configuration
information from the user manual and place it in the administrator manual, with
appropriate links between the two.

I've also done a general formatting cleanup to align with our style guide.

This change coincidentally addresses the following:

Connected to archivematica/Issues#170
Connected to archivematica/Issues#168

2018-09-14 01:25 UTC, ablwr requested changes

2018-09-14 01:25 UTC, ablwr commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +* **XLink Show**:
I think this and the line below need to say something?

2018-09-14 01:25 UTC, ablwr commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +
NICE work updating info for this super-legacy software :muscle:

2018-09-14 01:25 UTC, ablwr commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +.. important::
Maybe this message should go at the top of the instructions page instead of the bottom?

2018-09-14 01:25 UTC, ablwr commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +* **EAD DAO actuate**:
Should these not be empty either?

2018-09-14 22:40 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +* **XLink Show**:
Whoops!

2018-09-14 22:41 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +
:blush:

2018-09-14 22:41 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +* **EAD DAO actuate**:
Whoops x 2

2018-09-14 23:12 UTC, sallain commented
@ablwr should be all sorted if you wanna check again!

2018-09-15 17:25 UTC, ablwr approved these changes

2018-09-17 19:53 UTC, merged