Updates docs for thumbnail generation changes.
artefactual/archivematica-docs pull request #209
Opened 2018-10-10 23:03 UTC by sromkey

Updates relevant pages, primarily processing configuration settings, to reflect
new option for thumbnail generation. Pres planning, AIP structure and Access
pages refer to the processing configuration.

Also added line wrapping where relevant to AIP structure page ;)

2018-10-10 23:21 UTC, sallain requested changes
This looks good! I made a few minor suggestions. Thanks for fixing all the line lengths!!!

2018-10-10 23:21 UTC, sallain commented on user-manual/access/access.rst
> +If you have chosen to generate a DIP (dissemination information package) at the
Tiny consistency thing - at line 8, DIP is spelled out as Dissemination Information Package in title-case, here it's all lower-case. Title-case is probably best since it's a proper noun.

2018-10-10 23:21 UTC, sallain commented on user-manual/access/access.rst
> +`ContentDM <http://www.oclc.org/en/contentdm.html>`_.
Maybe indicate that the workflows are specific to access? i.e.

```
Access integration workflows also exist for `ArchivesSpace`_,
`Archivists' Toolkit`_ , and `ContentDM`_."
```

I've also been trying to move links to the bottom of the page as I come across them:

```
.. _`ArchivesSpace`: http://archivesspace.org/
.. _`Archivists' Toolkit`: http://www.archiviststoolkit.org/
.. _`ContentDM`: http://www.oclc.org/en/contentdm.html
```

2018-10-10 23:21 UTC, sallain commented on user-manual/archival-storage/aip-structure.rst
> +and three folders: logs, objects. and thumbnails.
There's an errant period here (`objects. and thumbnails.`). Can you fix it as part of this change? Thaaaaaanks :blush:

2018-10-10 23:21 UTC, sallain commented on user-manual/archival-storage/aip-structure.rst
>  role of the `METS file <https://wiki.archivematica.org/METS>`_ is to link
More link fixes (I'm obsessed):

Replace lines 96-100 with:

```
``/data/METS.uuid.xml`` contains the full `PREMIS`_ implementation (see PREMIS
metadata for original file, PREMIS metadata: normalized files, PREMIS metadata:
events, and PREMIS metadata: rights). The role of the `METS file`_ is to link
```

Add to the bottom of the doc:

```
.. _`PREMIS`: https://www.loc.gov/standards/premis/
.. _`METS file`: https://wiki.archivematica.org/METS
```

2018-10-11 16:55 UTC, joel-simpson approved these changes
Looks great - can't see any further details to improve on beyond what Sara already found.

2018-10-12 16:04 UTC, sromkey commented on user-manual/access/access.rst
> +`ContentDM <http://www.oclc.org/en/contentdm.html>`_.
Great idea for the links!

I'm not sure I agree that the workflows are all "access" related (although this does appear on the Access page...). ArchivesSpace and Archivists' Toolkit particularly are considered archival management tools, not necessarily just for access.

2018-10-12 16:05 UTC, sromkey commented on user-manual/archival-storage/aip-structure.rst
> +and three folders: logs, objects. and thumbnails.
Done!

2018-10-12 16:06 UTC, sromkey commented on user-manual/archival-storage/aip-structure.rst
>  role of the `METS file <https://wiki.archivematica.org/METS>`_ is to link
Done!

2018-10-12 16:07 UTC, sromkey commented on user-manual/access/access.rst
> +If you have chosen to generate a DIP (dissemination information package) at the
Done! Also going to fix the line lengths on this page, didn't catch them initially.

2018-10-12 16:20 UTC, sallain commented on user-manual/access/access.rst
> +`ContentDM <http://www.oclc.org/en/contentdm.html>`_.
Fair enough. I was mostly concerned with the sentence reading "also been developed to have workflows with ArchivesSpace and Archivists' Toolkit, ContentDM." - it's a bit awkward. But I didn't actually mention that in my feedback :joy:

2018-10-12 16:22 UTC, sromkey commented on user-manual/access/access.rst
> +`ContentDM <http://www.oclc.org/en/contentdm.html>`_.
I ended up using your suggestion anyway @sallain because in the context of this page I think it reads best. Thanks!

2018-10-12 16:55 UTC, closed without merging