Update backlog and appraisal tabs
artefactual/archivematica-docs pull request #311
Opened 2019-09-17 23:24 UTC by sallain

This started out as a pretty simple change to the Backlog tab page, just
intending to update some information... and then it spiralled out. Sorry
about that!

I've replaced screenshots throughout both backlog.rst and appraisal.rst
and updated formatting to match the style guide where necessary.

I've also substantially updated the information on both pages to be
clearer and more accurate. The

2019-09-18 03:09 UTC, ablwr requested changes

2019-09-18 03:09 UTC, ablwr commented on index.rst
>  * :ref:`Manage a backlog <manage-backlog>`
I think this page no longer exists as part of the backlog section and should be removed? I'm not sure if users of the docs actually see this page, but still.

2019-09-18 03:09 UTC, ablwr commented on index.rst
>  * :ref:`Manage a backlog <manage-backlog>`
I see this removed in the user-manual.rst though!

2019-09-18 03:10 UTC, ablwr commented
Only one extremely minor change. Beautiful, beautiful, beautiful docs work!!! :sob: :crown:

2019-09-19 16:41 UTC, sallain commented on index.rst
>  * :ref:`Manage a backlog <manage-backlog>`
Good catch, thanks! I'm surprised that Sphinx didn't catch this.

2019-09-19 16:44 UTC, ablwr approved these changes

2019-09-26 13:11 UTC, sarah-mason reviewed
It looks great! Loving the updated photos.

Just one small suggestion for the appraisal section (I hope that I've done it right).

2019-09-26 13:11 UTC, sarah-mason commented on user-manual/appraisal/appraisal.rst
>     Visualization showing formats by total size of the selected files
```suggestion
   Visualization showing total number of each format for the selected files
```

2019-09-26 15:31 UTC, sallain commented
@sarah-mason Great catch! Thank you!

2019-09-26 15:44 UTC, sarah-mason approved these changes
I was so excited to find something I read it like 5 times! Really excellent work, it's looking great and easy to follow!

2019-09-26 15:46 UTC, merged