avoid deprecated apt-key
artefactual/archivematica-docs pull request #436
Opened 2024-01-23 12:15 UTC by ssjeanderson

Avoids the use of apt-key, as it's deprecated, preventing several warnings during each apt update.

https://manpages.ubuntu.com/manpages/jammy/man8/apt-key.8.html

2024-01-23 22:21 UTC, replaceafill requested changes
This looks like a great change, thank you @ssjeanderson! Could we adjust the path of the Elasticsearch `.gpg` file as I suggested?

Once you submit your [contributor's agreement](https://github.com/artefactual/archivematica-docs/wiki/Contributor's-agreement) we'll merge this.

2024-01-23 22:21 UTC, replaceafill commented on admin-manual/installation-setup/installation/scripts/am-jammy-deb.sh
> +echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
```suggestion
curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /etc/apt/keyrings/elasticsearch-6.x.gpg
echo "deb [signed-by=/etc/apt/keyrings/elasticsearch-6.x.gpg] https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
```

2024-01-24 13:55 UTC, ssjeanderson commented
Sure. I just submitted the agreement. Thanks.

2024-01-24 14:02 UTC, merged

2024-01-24 14:02 UTC, replaceafill commented
Thank you for your contribution @ssjeanderson!