Add notes regarding ssl
artefactual/archivematica-docs pull request #55
Opened 2017-12-18 16:03 UTC by scollazo

2017-12-18 20:56 UTC, jhsimpson commented
This fixed #44

2017-12-20 23:01 UTC, kellyannewithane commented
@sevein or @sromkey can you CR?

2017-12-20 23:15 UTC, sromkey commented
It looks good to me in terms of formatting but I don't really know if this is enough/the right information, so let's wait for @sevein's input.

2017-12-20 23:52 UTC, sevein commented on admin-manual/installation/installation.rst
> +Archivematica can be configured for https following the sample configs for `dashboard
"configs" is not really a word, right? I think it should read "configurations".

2017-12-20 23:56 UTC, sevein requested changes
A few suggestions. I also think that we should capitalize acronyms, e.g. **HTTPS**, **SSL**, etc...

2017-12-20 23:56 UTC, sevein commented on admin-manual/installation/installation.rst
> +Using Archivematica through https
I think I would write it differently, perhaps: "Configure Archivematica with SSL".

I've searched "using nginx through https": only one result. It doesn't seem very common.

2017-12-20 23:56 UTC, sevein commented on admin-manual/installation/installation.rst
> + <https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/templates/etc/nginx/sites-available/dashboard-ssl.conf.j2>`_ and `storage-service <https://github.com/artefactual-labs/an
Missing period at the end of the sentence.

2017-12-20 23:56 UTC, sevein commented on admin-manual/installation/installation.rst
> +In order to obtain valid ssl certificates trusted by any browser, you can use `Let's Encrypt <https://letsencrypt.org>`_
Missing period at the end of the sentence.

2017-12-21 13:08 UTC, sevein approved these changes

2017-12-21 13:11 UTC, merged