Add autodeployment changes
artefactual/archivematica-docs pull request #71
Opened 2018-02-13 12:05 UTC by mamedin

This PR will:

* Update some CLI commands
* Add the new CLI command to configure and register pipeline
* Add new API section to the security document

These changes come from https://github.com/artefactual/archivematica/pull/681 , that includes this new CLI command and a major change in the API whitelist.

The

2018-02-13 22:05 UTC, sromkey commented
@scollazo Would you be able to review this PR when you have a chance? Thanks!

2018-02-15 21:47 UTC, scollazo requested changes

2018-02-15 21:47 UTC, scollazo commented on admin-manual/security/security.rst
> +There has been a major change in AM version 1.7 on the whitelist definition. In
Should we put this in bold? Or other format to draw attention to it

2018-02-16 16:59 UTC, mamedin commented
Hi Santi, I have set as "important" the paragraph you said. Thanks for the suggestion :)

2018-09-05 15:51 UTC, scollazo requested changes

2018-09-05 15:51 UTC, scollazo commented on admin-manual/installation/dashboard-config.rst
> +   /usr/share/python/archivematica-dashboard/bin/python manage.py createsuperuser
We should list the paramaters as we do for the dashboard manage.py command

2018-10-10 18:43 UTC, sallain commented
@mamedin Is this work going to be picked up? Or have these changes been reflected in other PRs since?

2018-10-22 17:48 UTC, mamedin commented
Hi, I updated this PR to AM 1.8.

Initially this PR had 3 commits, but now it is only needed this commit. It is ready for CR again.

2018-10-22 17:59 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +These commands configure the pipeline and register it on the storage service
s/storage service/Storage Service

2018-10-22 18:01 UTC, sallain requested changes

2018-10-22 18:01 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +
I think you can remove "shown after the installation would" for clarity.

2018-10-22 18:01 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +configuration method.
Provide a link to the web config method if possible.

2018-10-22 18:01 UTC, sallain commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +      For example: "test", "4e5f32ab2aefd3577e1b19a2de5d4dd65f90101a".
s/Api key/API key

2018-10-22 18:10 UTC, sevein commented on admin-manual/installation-setup/customization/dashboard-config.rst
> +Where:
In the list below, can you use [inline literals](http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup) for things like `api-key`, `test` etc?

Also the indentation in the enumeration is not needed, the fact that is there causes the HTML to be rendered inside a `blockquote`, see:

![image](https://user-images.githubusercontent.com/606459/47310121-0b650200-d5eb-11e8-88cf-ca546861ef46.png)

2018-10-23 09:39 UTC, mamedin commented
Thanks Sara and Jesus for your suggestions :). I added them and it is ready for CR again.

2018-10-23 13:49 UTC, sevein approved these changes
Thanks!

2018-10-23 16:03 UTC, sallain approved these changes

2018-11-01 10:10 UTC, merged